/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
import '@vue/runtime-core'

export {}

declare module '@vue/runtime-core' {
  export interface GlobalComponents {
    HelloWorld: typeof import('./src/motoko_student_wall_dapp_frontend/components/HelloWorld.vue')['default']
    IconCommunity: typeof import('./src/motoko_student_wall_dapp_frontend/components/icons/IconCommunity.vue')['default']
    IconDocumentation: typeof import('./src/motoko_student_wall_dapp_frontend/components/icons/IconDocumentation.vue')['default']
    IconEcosystem: typeof import('./src/motoko_student_wall_dapp_frontend/components/icons/IconEcosystem.vue')['default']
    IconSupport: typeof import('./src/motoko_student_wall_dapp_frontend/components/icons/IconSupport.vue')['default']
    IconTooling: typeof import('./src/motoko_student_wall_dapp_frontend/components/icons/IconTooling.vue')['default']
    IIcOutlineWbSunny: typeof import('~icons/ic/outline-wb-sunny')['default']
    IMdiWeatherNight: typeof import('~icons/mdi/weather-night')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    TheHeader: typeof import('./src/motoko_student_wall_dapp_frontend/components/TheHeader.vue')['default']
    TheThemeSwitch: typeof import('./src/motoko_student_wall_dapp_frontend/components/TheThemeSwitch.vue')['default']
    TheWelcome: typeof import('./src/motoko_student_wall_dapp_frontend/components/TheWelcome.vue')['default']
    WelcomeItem: typeof import('./src/motoko_student_wall_dapp_frontend/components/WelcomeItem.vue')['default']
  }
}
